### ISSUE TITLE
readme notes branches per video - only seems to be one branch available

### ISSUE THREAD

**Issue by stuzenz** [StephenGrider/ReactNativeReduxCasts#1]
Hi Stephen,

Can you just doublecheck if you have the repo set up as you thought you had. The readme notes multiple branches mapped to videos - but I can only see one.

It might be good to give the clone command for cloning all branches locally too. Something I always have to google and figure out when I need it.

Cheers,
Stu

**Comment by StephenGrider** [comment]
Fixed, thanks for mentioning this!

**Comment by stuzenz** [comment]
no problem - thnx for the course!
